#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# =============================================================================
# NCCL 性能测试示例脚本
# 在所有节点上运行 NCCL all_reduce 性能测试
#
# 注意：此脚本由 default-launcher.sh 调用
# 以下功能已由 launcher 完成，无需重复实现：
# - SSH 服务配置
# - 节点发现和连通性测试
# - 物理拓扑发现和优化排序
# - 生成 MPI hostfile (/etc/job-worker-services.txt)
# =============================================================================

echo "=============================================="
echo "NCCL Performance Test Starting..."
echo "=============================================="

# -----------------------------------------------------------------------------
# 只在主节点（rank 0）上执行 MPI 启动
# 其他节点会由 launcher 保持运行（sleepInfinity=true），等待 MPI 通过 SSH 连接
# -----------------------------------------------------------------------------
if [ "$JOB_COMPLETION_INDEX" -ne "0" ]; then
  echo "This is worker node $JOB_COMPLETION_INDEX."
  echo "SSH daemon running on port 2222."
  echo "Waiting for master node to initiate NCCL test via MPI/SSH..."
  # 直接退出，launcher 会 sleep infinity 保持容器运行
  exit 0
fi

echo "This is master node, initiating NCCL test across all nodes..."

# -----------------------------------------------------------------------------
# 1. 收集 NCCL 环境变量
# -----------------------------------------------------------------------------
echo ""
echo "Step 1: Collecting NCCL environment variables..."

# 收集所有 NCCL 环境变量并转换为 MPI 参数格式
readarray -d "" nccl_environment < <(env | grep -e "^NCCL_" | sed 's/^/-x /' | tr '\n' '\0')

echo "Detected NCCL environment:"
for nccl_variable in "${nccl_environment[@]}"; do
  echo "  $nccl_variable"
done

# 检查 hostfile 是否存在（由 launcher 生成）
if [ ! -f /etc/job-worker-services.txt ]; then
  echo "ERROR: /etc/job-worker-services.txt not found!"
  echo "This file should be generated by default-launcher.sh"
  exit 1
fi

echo ""
echo "Using MPI hostfile (generated by launcher):"
cat /etc/job-worker-services.txt | sed 's/^/  /'

# -----------------------------------------------------------------------------
# 2. 基本连通性测试
# -----------------------------------------------------------------------------
echo ""
echo "Step 2: Testing basic connectivity..."
mpirun --allow-run-as-root \
  -np $((8*$NNODES)) \
  --hostfile /etc/job-worker-services.txt \
  --mca orte_keep_fqdn_hostnames t \
  --mca plm_rsh_agent "ssh -q -o LogLevel=ERROR -o StrictHostKeyChecking=no -p 2222" \
  hostname

if [ $? -ne 0 ]; then
  echo "ERROR: Connectivity test failed!"
  exit 1
fi
echo "Connectivity test passed!"

# -----------------------------------------------------------------------------
# 3. NCCL All-Reduce 性能测试
# -----------------------------------------------------------------------------
echo ""
echo "Step 3: Running NCCL all_reduce performance test..."
echo "Test parameters:"
echo "  - Nodes: $NNODES"
echo "  - GPUs per node: 8"
echo "  - Total GPUs: $((8*$NNODES))"
echo "  - Message sizes: 1G to 8G"
echo ""

# 构建 worker 命令
# 通过 set_nccl_env.sh 初始化 NCCL 环境（GIB 自动管理）
# unset TORCH_NCCL_USE_COMM_NONBLOCKING 以消除 GIB shim 警告
worker_command="unset TORCH_NCCL_USE_COMM_NONBLOCKING && "
worker_command+="source /usr/local/gib/scripts/set_nccl_env.sh && "
worker_command+="cd /third_party/nccl-tests && "
worker_command+="./build/all_reduce_perf -b 1G -e 8G -f 2 -n 5 -g 1 -w 5"

mpirun --allow-run-as-root \
  -n "$((8*$NNODES))" \
  --hostfile /etc/job-worker-services.txt \
  --mca orte_keep_fqdn_hostnames t \
  --mca plm_rsh_agent "ssh -q -o LogLevel=ERROR -o StrictHostKeyChecking=no -p 2222" \
  -x LD_LIBRARY_PATH \
  bash -c "$worker_command"

NCCL_EXIT_CODE=$?

echo ""
echo "=============================================="
if [ $NCCL_EXIT_CODE -eq 0 ]; then
  echo "NCCL Performance Test Completed Successfully!"
else
  echo "NCCL Performance Test Failed with exit code: $NCCL_EXIT_CODE"
fi
echo "=============================================="

exit $NCCL_EXIT_CODE
