# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Headless Service for pod-to-pod communication
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  clusterIP: None
  # 允许 DNS 解析未就绪的 Pod（分布式训练需要所有节点互相发现）
  # 当 Pod 卡在 Init 容器时（如 Lustre 挂载），仍需要能够解析其 DNS
  publishNotReadyAddresses: true
  selector:
    jobset.sigs.k8s.io/jobset-name: "{{ .Release.Name }}"
