apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deepep-installer
  namespace: kube-system
  labels:
    k8s-app: deepep-installer
spec:
  selector:
    matchLabels:
      k8s-app: deepep-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: deepep-installer
        k8s-app: deepep-installer
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-accelerator
                    operator: In
                    values:
                      - nvidia-b200
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - a4-highgpu-ubuntu
                  # - key: kubernetes.io/hostname
                  #   operator: In
                  #   values:
                  #     - "gke-chrisya-gke-a4-a4-spot-ubuntu-c6c51451-nbyx"
      tolerations:
        - operator: "Exists"
      hostNetwork: true
      hostPID: true
      volumes:
        - name: root
          hostPath:
            path: /
      initContainers:
        - image: gke.gcr.io/gke-distroless/bash:latest
          name: deepep-installer
          resources:
            requests:
              cpu: 150m
          securityContext:
            privileged: true
          volumeMounts:
            - name: root
              mountPath: /
          env:
            - name: NVSHMEM_IBGDA_SUPPORT
              value: "1"
            - name: NVSHMEM_USE_GDRCOPY
              value: "1"
            - name: GDRCOPY_HOME
              value: /opt/deepep/gdrcopy
            - name: NVSHMEM_HOME
              value: /opt/deepep/nvshmem
            - name: USE_NVPEERMEM
              value: "0"
            - name: CUDA_HOME
              value: /usr/local/cuda
            - name: TORCH_CUDA_ARCH_LIST_B200
              value: "10.0"
            - name: TORCH_CUDA_ARCH_LIST_H200
              value: "9.0"
          command: ["sleep", "infinity"]

      containers:
        - image: "gke.gcr.io/pause:3.8@sha256:880e63f94b145e46f1b1082bb71b85e21f16b99b180b9996407d61240ceb9830"
          name: pause